In [1]:
import pandas as pd
import numpy as np

### Q1 Pandas version

In [2]:
pd.__version__

'3.0.6'

### Getting the data

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Q2 Records count

In [5]:
df.shape[0]

10000

### Q2 Fuel types

In [6]:
df["fuel_type"].nunique()

3

### Q4 Missing values

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

### Q5 Max fuel efficiency

In [8]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

### Q6 Median value of horsepower

In [9]:
df["horsepower"].median()

np.float64(254.0)

In [10]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [11]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [12]:
df["horsepower"].median()

np.float64(252.0)

### Q7 Sum of weights

In [13]:
#All cars from Asia
asia_cars = df[
    df["origin"] == "Asia"
]
print(asia_cars)

      model_year origin fuel_type         drivetrain  num_doors  \
2           1996   Asia  Gasoline  Front-wheel drive          5
6           1992   Asia  Gasoline  Front-wheel drive          2
8           1997   Asia  Gasoline   Rear-wheel drive          3
10          1978   Asia  Gasoline    All-wheel drive          3
15          2007   Asia    Diesel  Front-wheel drive          4
...          ...    ...       ...                ...        ...
9984        2011   Asia  Gasoline  Front-wheel drive          3
9987        2004   Asia    Diesel    All-wheel drive          3
9990        1975   Asia    Diesel  Front-wheel drive          4
9994        1993   Asia  Gasoline   Rear-wheel drive          2
9996        1993   Asia  Gasoline    All-wheel drive          2

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
2                    2320              6       267.0            4240
6                    2270              6       250.0            4310
8                    2330              6       251.0            4230
10                   2410              6       252.0            4420
15                   2170              5       226.0            3950
...                   ...            ...         ...             ...
9984                 2410              6       256.0            4610
9987                 2180              6       266.0            4530
9990                 1940              6       236.0            3630
9994                 2360              6       257.0            4610
9996                 2300              6       244.0            4370

      acceleration  fuel_efficiency_mpg
2             17.3                 27.5
6             21.7                 26.8
8             19.5                 30.9
10            19.5                 26.8
15            18.0                 35.4
...            ...                  ...
9984          20.2                 32.4
9987          18.6                 29.0
9990          19.7                 32.4
9994          22.2                 30.1
9996          19.0                 30.0

[2994 rows x 11 columns]

In [14]:
#Only columns vehicle_weight and model_year
vw_my = asia_cars[
    ["vehicle_weight","model_year"]
    ]
print(vw_my)

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [21]:
#First 7 values
vw_my.head(n=7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [29]:
#Underlying NumPy array
X = vw_my.head(n=7).values
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [30]:
#Matrix-matrix multiplication between the transpose of X and X
XTX = X.T.dot(X)
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [31]:
#Inverse of XTX
XTX_inv = np.linalg.pinv(XTX)
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [32]:
#Creating array y
y = np.array([1100,1300,800,900,1000,1100,1200])
print(y)

[1100 1300  800  900 1000 1100 1200]

In [38]:
#Product of inverse of XTX and X.T
w = XTX_inv.dot(X.T)

In [39]:
X.shape

(7, 2)